import { QueryResponse } from "./api";

export const MOCK_DEMO_RESPONSES: Record<string, QueryResponse> = {
  // Scenario 1: Broad Dataset Analysis
  "scenario_1": {
    query_id: "plan-mock-demo-01",
    query: "Analyse this dataset for suspicious activity",
    parsed_intent: {
      query: "Analyse this dataset for suspicious activity",
      intent: "broad_analysis",
      filters: {},
      entities: [],
      pattern: null,
      time_window: null,
    },
    execution_plan: {
      plan_id: "plan-mock-demo-01",
      query: "Analyse this dataset for suspicious activity",
      detected_intent: "broad_analysis",
      active_filters: {},
      target_entities: [],
      steps: [
        {
          step_number: 1,
          tool_name: "eda",
          description: "Generate exploratory data analysis, transaction counts, volume distributions, and counterparty summaries.",
          parameters: {},
          status: "COMPLETED",
          result_summary: "EDA completed: 20 transactions analyzed across 4 currencies.",
        },
        {
          step_number: 2,
          tool_name: "features",
          description: "Engineer rolling transaction velocities, sub-$10k counts, and network graph degrees.",
          parameters: {},
          status: "COMPLETED",
          result_summary: "Engineered 7 rolling behavioral features.",
        },
        {
          step_number: 3,
          tool_name: "detectors_ml",
          description: "Execute Isolation Forest anomaly detector on engineered feature set to compute statistical anomaly scores.",
          parameters: { contamination: 0.05 },
          status: "COMPLETED",
          result_summary: "Isolation Forest flagged 2 statistical anomaly instances.",
        },
        {
          step_number: 4,
          tool_name: "detectors_rules",
          description: "Evaluate deterministic AML rule detectors (structuring, smurfing, rapid layering, fan-out, velocity).",
          parameters: {},
          status: "COMPLETED",
          result_summary: "Rule detectors produced 3 deterministic AML flags.",
        },
        {
          step_number: 5,
          tool_name: "risk",
          description: "Fuse deterministic rule flags with ML anomaly scores into normalized risk scores and categorical tiers.",
          parameters: {},
          status: "COMPLETED",
          result_summary: "Risk fusion completed: CRITICAL risk (score: 0.8850).",
        },
        {
          step_number: 6,
          tool_name: "explain",
          description: "Generate natural language explainability narratives and evidence citations for all flagged findings.",
          parameters: {},
          status: "COMPLETED",
          result_summary: "Generated 3 typology-tied explainability narratives.",
        },
      ],
      invoked_tools: ["eda", "features", "detectors_ml", "detectors_rules", "risk", "explain"],
      skipped_tools: [],
      reasoning: "Full end-to-end AML investigative pipeline scheduled: baseline EDA profiling, rolling feature engineering, Isolation Forest unsupervised anomaly detection, comprehensive deterministic AML rule evaluation, hybrid risk score fusion, and compliance explainability.",
      created_at: new Date().toISOString(),
    },
    flags: [
      {
        flag_id: "FLAG-MOCK-001",
        rule_id: "RULE_STRUCTURING_01",
        rule_name: "Outbound Structuring below Reporting Threshold",
        severity: "CRITICAL",
        entity_id: "ACC015",
        transaction_ids: ["TX_15", "TX_16", "TX_17"],
        typology: "Structuring",
        reason: "Account ACC015 conducted 3 outbound transactions between $7,500.00 and $9,999.99 totaling $29,840.00 within 0.5 hours, indicating deliberate CTR evasion.",
        evidence: {
          tx_count: 3,
          total_amount: 29840.0,
          min_tx_amount: 9900.0,
          max_tx_amount: 9990.0,
          time_span_hours: 0.5,
        },
        timestamp: new Date().toISOString(),
      },
      {
        flag_id: "FLAG-MOCK-002",
        rule_id: "RULE_RAPID_LAYERING_01",
        rule_name: "Rapid Layering / Pass-Through Conduit",
        severity: "HIGH",
        entity_id: "ACC021",
        transaction_ids: ["TX_18", "TX_19"],
        typology: "Pass-through",
        reason: "Account ACC021 received $25,000.00 and transferred out $18,000.00 (72.0% turnover) within 25.0 minutes, matching money mule pass-through behavior.",
        evidence: {
          in_amount: 25000.0,
          out_amount: 18000.0,
          pass_through_ratio: 0.72,
          time_delta_minutes: 25.0,
        },
        timestamp: new Date().toISOString(),
      },
      {
        flag_id: "FLAG-MOCK-003",
        rule_id: "RULE_FAN_OUT_01",
        rule_name: "High Fan-Out Fund Dispersion",
        severity: "HIGH",
        entity_id: "ACC015",
        transaction_ids: ["TX_15", "TX_16", "TX_17"],
        typology: "Fan-out",
        reason: "Source account ACC015 dispersed $29,840.00 across 3 distinct beneficiary accounts (ACC016, ACC017, ACC018) in under 30 minutes.",
        evidence: {
          distinct_recipients: 3,
          total_amount: 29840.0,
          sample_recipients: ["ACC016", "ACC017", "ACC018"],
        },
        timestamp: new Date().toISOString(),
      },
    ],
    risk_result: {
      result_id: "RISK-MOCK-001",
      entity_id: null,
      transaction_id: null,
      risk_score: 0.885,
      risk_tier: "CRITICAL",
      flags: [],
      rule_score: 0.85,
      ml_score: 0.92,
      summary: "Investigation dataset sample evaluated at CRITICAL risk (score: 0.8850) with 3 triggered AML detection flags (Structuring, Pass-through, Fan-out). Isolation Forest ML anomaly score evaluated at 0.92 (elevated). Primary finding: Account ACC015 conducted 3 outbound structuring transactions.",
      evidence_summary: {
        total_flags: 3,
        total_transactions: 20,
        flagged_typologies: ["Structuring", "Pass-through", "Fan-out"],
        fused_risk_score: 0.885,
      },
      created_at: new Date().toISOString(),
    },
    synthesized_result: {
      executive_summary: "Comprehensive AML investigation completed across dataset. Identified multiple coordinated financial crime patterns including high-confidence sub-$10,000 structuring and rapid conduit layering.",
      key_findings: [
        "Structuring Detection: Account ACC015 conducted 3 rapid transfers of $9,990, $9,950, and $9,900 to multiple counterparties within 30 minutes (TX_15, TX_16, TX_17).",
        "Pass-Through Conduit: Account ACC021 rapidly transferred out 72% of received wire funds within 25 minutes (TX_18, TX_19).",
        "ML Anomaly Scoring: Isolation Forest identified statistical outlier behavior in account ACC015's out-degree transaction velocity.",
      ],
      cited_transaction_ids: ["TX_15", "TX_16", "TX_17", "TX_18", "TX_19"],
      limitations: [],
    },
    trace: {
      trace_id: "trace-mock-01",
      query_id: "plan-mock-demo-01",
      detected_intent: "broad_analysis",
      active_filters: {},
      invoked_tools: ["eda", "features", "detectors_ml", "detectors_rules", "risk", "explain"],
      skipped_tools: [],
      execution_timings_ms: { eda: 12.4, features: 8.1, detectors_ml: 24.6, detectors_rules: 15.2, risk: 4.8, explain: 18.3 },
      total_execution_time_ms: 83.4,
      status: "SUCCESS",
      error_message: null,
      created_at: new Date().toISOString(),
    },
    explanations: [
      {
        flag_id: "FLAG-MOCK-001",
        typology: "Structuring",
        explanation: "Account ACC015 exhibited systematic structuring behavior by sending 3 wire transfers just below the $10,000 regulatory reporting threshold within 30 minutes.",
      },
      {
        flag_id: "FLAG-MOCK-002",
        typology: "Pass-through",
        explanation: "Account ACC021 functioned as a rapid money-mule layering conduit by disbursing $18,000 immediately after receiving $25,000.",
      },
    ],
    eda_summary: {
      total_transactions: 20,
      total_volume: 165490.0,
      distinct_accounts: 22,
    },
  },

  // Scenario 2: Structuring Patterns (30d) -> Skips EDA and ML
  "scenario_2": {
    query_id: "plan-mock-demo-02",
    query: "Find structuring patterns in the last 30 days",
    parsed_intent: {
      query: "Find structuring patterns in the last 30 days",
      intent: "pattern_detection",
      filters: { time_window_days: 30, pattern: "structuring" },
      entities: [],
      pattern: "structuring",
      time_window: { type: "relative", value: 30, unit: "days", raw_text: "last 30 days" },
    },
    execution_plan: {
      plan_id: "plan-mock-demo-02",
      query: "Find structuring patterns in the last 30 days",
      detected_intent: "pattern_detection",
      active_filters: { time_window_days: 30, pattern: "structuring" },
      target_entities: [],
      steps: [
        {
          step_number: 1,
          tool_name: "detectors_rules",
          description: "Execute deterministic AML detector for 'structuring' typology with active temporal and threshold filters.",
          parameters: { rules: ["structuring"], time_window_days: 30 },
          status: "COMPLETED",
          result_summary: "Structuring detector flagged 1 high-severity entity pattern.",
        },
        {
          step_number: 2,
          tool_name: "risk",
          description: "Calculate risk severity and tier categorization for detected typology flags.",
          parameters: {},
          status: "COMPLETED",
          result_summary: "Risk assessment completed: HIGH risk.",
        },
        {
          step_number: 3,
          tool_name: "explain",
          description: "Synthesize typology-specific investigative explanations citing supporting transactions.",
          parameters: {},
          status: "COMPLETED",
          result_summary: "Generated 1 structuring explanation citing 3 transaction IDs.",
        },
      ],
      invoked_tools: ["detectors_rules", "risk", "explain"],
      skipped_tools: [
        {
          tool_name: "eda",
          reason: "EDA skipped: Query targets a specific typology pattern with temporal constraints rather than overall baseline profiling.",
        },
        {
          tool_name: "detectors_ml",
          reason: "ML Anomaly Detection skipped: Query specifically searches for deterministic rule-based typology patterns where thresholds are strictly defined.",
        },
        {
          tool_name: "features",
          reason: "Feature engineering skipped: Deterministic rule detector operates directly on filtered transaction time series.",
        },
      ],
      reasoning: "Targeted rule investigation plan generated for 'structuring' typology with temporal/threshold constraints. Unsupervised ML and exploratory profiling are bypassed to minimize latency and focus execution on deterministic rule evaluation.",
      created_at: new Date().toISOString(),
    },
    flags: [
      {
        flag_id: "FLAG-MOCK-STRUCT-01",
        rule_id: "RULE_STRUCTURING_01",
        rule_name: "Outbound Structuring below Reporting Threshold",
        severity: "CRITICAL",
        entity_id: "ACC015",
        transaction_ids: ["TX_15", "TX_16", "TX_17"],
        typology: "Structuring",
        reason: "Account ACC015 conducted 3 outbound transactions between $7,500.00 and $9,999.99 totaling $29,840.00 within 30 minutes, evading Bank Secrecy Act thresholds.",
        evidence: {
          tx_count: 3,
          total_amount: 29840.0,
          min_tx_amount: 9900.0,
          max_tx_amount: 9990.0,
          time_span_hours: 0.5,
          window_threshold_hours: 72.0,
        },
        timestamp: new Date().toISOString(),
      },
    ],
    risk_result: {
      result_id: "RISK-MOCK-002",
      entity_id: "ACC015",
      transaction_id: null,
      risk_score: 0.75,
      risk_tier: "CRITICAL",
      flags: [],
      rule_score: 0.75,
      ml_score: null,
      summary: "Account ACC015 evaluated at CRITICAL risk (score: 0.7500) with 1 triggered AML detection flag (Structuring). Primary finding: 3 transactions below $10,000.",
      evidence_summary: {
        total_flags: 1,
        rule_score: 0.75,
        ml_score: null,
      },
      created_at: new Date().toISOString(),
    },
    synthesized_result: {
      executive_summary: "Structuring pattern search over the 30-day temporal window identified deliberate CTR avoidance activity for account ACC015.",
      key_findings: [
        "Account ACC015 performed 3 consecutive transfers of $9,990.00, $9,950.00, and $9,900.00 within 30 minutes (TX_15, TX_16, TX_17).",
        "Total structured outbound volume: $29,840.00 across recipient accounts ACC016, ACC017, and ACC018.",
      ],
      cited_transaction_ids: ["TX_15", "TX_16", "TX_17"],
      limitations: [
        "Tool 'eda' was skipped: Query targets a specific typology pattern with temporal constraints rather than overall baseline profiling.",
        "Tool 'detectors_ml' was skipped: Query specifically searches for deterministic rule-based typology patterns.",
      ],
    },
    trace: {
      trace_id: "trace-mock-02",
      query_id: "plan-mock-demo-02",
      detected_intent: "pattern_detection",
      active_filters: { time_window_days: 30, pattern: "structuring" },
      invoked_tools: ["detectors_rules", "risk", "explain"],
      skipped_tools: [
        { tool_name: "eda", reason: "Targeted typology query" },
        { tool_name: "detectors_ml", reason: "Deterministic threshold query" },
      ],
      execution_timings_ms: { detectors_rules: 8.2, risk: 3.1, explain: 12.0 },
      total_execution_time_ms: 23.3,
      status: "SUCCESS",
      error_message: null,
      created_at: new Date().toISOString(),
    },
    explanations: [
      {
        flag_id: "FLAG-MOCK-STRUCT-01",
        typology: "Structuring",
        explanation: "Account ACC015 triggered RULE_STRUCTURING_01 due to rapid sub-$10k disbursements totaling $29,840.00.",
      },
    ],
    eda_summary: null,
  },

  // Scenario 3: Aggregation -> Skips ML
  "scenario_3": {
    query_id: "plan-mock-demo-03",
    query: "Which customers made 10+ transactions under $10,000?",
    parsed_intent: {
      query: "Which customers made 10+ transactions under $10,000?",
      intent: "aggregation",
      filters: { min_transaction_count: 10, max_transaction_amount: 10000.0 },
      entities: [],
      pattern: null,
      time_window: null,
    },
    execution_plan: {
      plan_id: "plan-mock-demo-03",
      query: "Which customers made 10+ transactions under $10,000?",
      detected_intent: "aggregation",
      active_filters: { min_transaction_count: 10, max_transaction_amount: 10000.0 },
      target_entities: [],
      steps: [
        {
          step_number: 1,
          tool_name: "features",
          description: "Calculate transaction frequencies, aggregated volumes, and threshold counts per account.",
          parameters: { min_transaction_count: 10, max_transaction_amount: 10000.0 },
          status: "COMPLETED",
          result_summary: "Aggregated transaction counts for 22 accounts.",
        },
        {
          step_number: 2,
          tool_name: "detectors_rules",
          description: "Apply threshold rules and identify candidate accounts matching aggregation criteria.",
          parameters: { rules: ["structuring", "velocity"] },
          status: "COMPLETED",
          result_summary: "Identified 2 candidate accounts matching threshold criteria.",
        },
        {
          step_number: 3,
          tool_name: "risk",
          description: "Assess risk scores and tier categorizations for accounts meeting aggregation criteria.",
          parameters: {},
          status: "COMPLETED",
          result_summary: "Risk tier assessed as HIGH for matching accounts.",
        },
        {
          step_number: 4,
          tool_name: "explain",
          description: "Generate findings breakdown and transaction evidence citations for matching entities.",
          parameters: {},
          status: "COMPLETED",
          result_summary: "Compiled aggregation findings breakdown.",
        },
      ],
      invoked_tools: ["features", "detectors_rules", "risk", "explain"],
      skipped_tools: [
        {
          tool_name: "detectors_ml",
          reason: "ML Anomaly Detection skipped: Query requires deterministic aggregation and exact threshold counting; unsupervised ML is not applicable.",
        },
        {
          tool_name: "eda",
          reason: "Global EDA skipped: Aggregation analysis directly evaluates entity transaction frequencies and threshold criteria.",
        },
      ],
      reasoning: "Deterministic aggregation pipeline scheduled to compute account-level transaction counts and amount threshold filters. Machine learning anomaly scoring is skipped as the query specifies exact deterministic filter criteria.",
      created_at: new Date().toISOString(),
    },
    flags: [
      {
        flag_id: "FLAG-MOCK-AGG-01",
        rule_id: "RULE_HIGH_VELOCITY_01",
        rule_name: "High Outbound Velocity Burst",
        severity: "HIGH",
        entity_id: "ACC015",
        transaction_ids: ["TX_15", "TX_16", "TX_17"],
        typology: "Velocity Spike",
        reason: "Account ACC015 conducted 3 high-value transactions under $10,000 totaling $29,840.00.",
        evidence: { tx_count: 3, total_amount: 29840.0 },
        timestamp: new Date().toISOString(),
      },
    ],
    risk_result: {
      result_id: "RISK-MOCK-003",
      entity_id: "ACC015",
      transaction_id: null,
      risk_score: 0.65,
      risk_tier: "HIGH",
      flags: [],
      rule_score: 0.65,
      ml_score: null,
      summary: "Aggregation evaluation identified ACC015 as primary high-velocity entity with sub-$10k transaction concentration.",
      evidence_summary: {
        total_flags: 1,
        fused_risk_score: 0.65,
      },
      created_at: new Date().toISOString(),
    },
    synthesized_result: {
      executive_summary: "Aggregation query executed for transactions under $10,000. Customer ACC015 matched high-frequency sub-threshold criteria.",
      key_findings: [
        "Account ACC015 conducted 3 transfers under $10,000 totaling $29,840.00.",
        "Deterministic threshold filters satisfied with zero ML false-positive noise.",
      ],
      cited_transaction_ids: ["TX_15", "TX_16", "TX_17"],
      limitations: [
        "Tool 'detectors_ml' was skipped: Unsupervised ML is not applicable for deterministic aggregation counts.",
      ],
    },
    trace: {
      trace_id: "trace-mock-03",
      query_id: "plan-mock-demo-03",
      detected_intent: "aggregation",
      active_filters: { min_transaction_count: 10, max_transaction_amount: 10000.0 },
      invoked_tools: ["features", "detectors_rules", "risk", "explain"],
      skipped_tools: [{ tool_name: "detectors_ml", reason: "Deterministic aggregation" }],
      execution_timings_ms: { features: 10.2, detectors_rules: 9.4, risk: 2.8, explain: 11.1 },
      total_execution_time_ms: 33.5,
      status: "SUCCESS",
      error_message: null,
      created_at: new Date().toISOString(),
    },
    explanations: [],
    eda_summary: null,
  },

  // Scenario 4: Single Entity Drill-Down (Customer 4521)
  "scenario_4": {
    query_id: "plan-mock-demo-04",
    query: "Is customer 4521 suspicious?",
    parsed_intent: {
      query: "Is customer 4521 suspicious?",
      intent: "entity_investigation",
      filters: {},
      entities: ["4521"],
      pattern: null,
      time_window: null,
    },
    execution_plan: {
      plan_id: "plan-mock-demo-04",
      query: "Is customer 4521 suspicious?",
      detected_intent: "entity_investigation",
      active_filters: {},
      target_entities: ["4521"],
      steps: [
        {
          step_number: 1,
          tool_name: "eda",
          description: "Profile transaction volume, flow distribution, and top counterparties for entity 4521.",
          parameters: { entity_id: "4521" },
          status: "COMPLETED",
          result_summary: "Profiled account 4521: 4 transactions with $55,000 volume.",
        },
        {
          step_number: 2,
          tool_name: "features",
          description: "Compute rolling velocities and graph degree metrics for entity 4521.",
          parameters: { entity_id: "4521" },
          status: "COMPLETED",
          result_summary: "Extracted entity velocity and fan-out metrics.",
        },
        {
          step_number: 3,
          tool_name: "detectors_rules",
          description: "Evaluate all deterministic AML rules for entity 4521.",
          parameters: { entity_id: "4521" },
          status: "COMPLETED",
          result_summary: "Triggered 2 high-severity rule flags for 4521.",
        },
        {
          step_number: 4,
          tool_name: "detectors_ml",
          description: "Calculate ML anomaly score for entity 4521.",
          parameters: { entity_id: "4521" },
          status: "COMPLETED",
          result_summary: "Isolation Forest anomaly score: 0.94 (severe outlier).",
        },
        {
          step_number: 5,
          tool_name: "risk",
          description: "Fuse rule flags and ML anomaly score into comprehensive 360° risk evaluation for entity 4521.",
          parameters: { entity_id: "4521" },
          status: "COMPLETED",
          result_summary: "Fused 360° risk score: 0.9250 (CRITICAL).",
        },
        {
          step_number: 6,
          tool_name: "explain",
          description: "Generate natural language investigative breakdown and evidence summary for entity 4521.",
          parameters: { entity_id: "4521" },
          status: "COMPLETED",
          result_summary: "Synthesized full compliance narrative.",
        },
      ],
      invoked_tools: ["eda", "features", "detectors_rules", "detectors_ml", "risk", "explain"],
      skipped_tools: [],
      reasoning: "Targeted 360° entity drill-down plan generated for entity 4521. Combines entity-level profiling, feature metrics, rule evaluation, ML anomaly scoring, hybrid risk fusion, and evidence citations.",
      created_at: new Date().toISOString(),
    },
    flags: [
      {
        flag_id: "FLAG-MOCK-ENT-01",
        rule_id: "RULE_RAPID_LAYERING_01",
        rule_name: "Rapid Layering / Pass-Through Conduit",
        severity: "CRITICAL",
        entity_id: "4521",
        transaction_ids: ["TX_18", "TX_19"],
        typology: "Pass-through",
        reason: "Customer 4521 acted as a rapid pass-through conduit, receiving $25,000.00 and transferring out $18,000.00 (72.0% turnover) within 25.0 minutes.",
        evidence: {
          in_amount: 25000.0,
          out_amount: 18000.0,
          pass_through_ratio: 0.72,
          time_delta_minutes: 25.0,
        },
        timestamp: new Date().toISOString(),
      },
      {
        flag_id: "FLAG-MOCK-ENT-02",
        rule_id: "RULE_FAN_OUT_01",
        rule_name: "High Fan-Out Fund Dispersion",
        severity: "HIGH",
        entity_id: "4521",
        transaction_ids: ["TX_15", "TX_16", "TX_17"],
        typology: "Fan-out",
        reason: "Customer 4521 dispersed funds to 3 distinct counterparties in rapid succession.",
        evidence: {
          distinct_recipients: 3,
          total_amount: 29840.0,
        },
        timestamp: new Date().toISOString(),
      },
    ],
    risk_result: {
      result_id: "RISK-MOCK-004",
      entity_id: "4521",
      transaction_id: null,
      risk_score: 0.925,
      risk_tier: "CRITICAL",
      flags: [],
      rule_score: 0.9,
      ml_score: 0.94,
      summary: "Customer 4521 evaluated at CRITICAL risk (score: 0.9250) with 2 triggered AML detection flags (Pass-through, Fan-out). Isolation Forest ML anomaly score evaluated at 0.94 (elevated). Primary finding: Pass-through mule conduit activity.",
      evidence_summary: {
        entity_id: "4521",
        total_flags: 2,
        rule_score: 0.9,
        ml_score: 0.94,
        fused_risk_score: 0.925,
      },
      created_at: new Date().toISOString(),
    },
    synthesized_result: {
      executive_summary: "Targeted 360° assessment for Customer 4521 concluded with a CRITICAL risk rating (0.9250). Immediate compliance review / SAR filing recommended.",
      key_findings: [
        "Customer 4521 received $25,000 and immediately disbursed $18,000 to high-risk counterparty ACC022 within 25 minutes (TX_18, TX_19).",
        "Dispersed $29,840 across 3 new accounts under the $10,000 CTR reporting threshold.",
        "Unsupervised Isolation Forest model scored this entity in the 99th percentile of network anomalies.",
      ],
      cited_transaction_ids: ["TX_15", "TX_16", "TX_17", "TX_18", "TX_19"],
      limitations: [],
    },
    trace: {
      trace_id: "trace-mock-04",
      query_id: "plan-mock-demo-04",
      detected_intent: "entity_investigation",
      active_filters: {},
      invoked_tools: ["eda", "features", "detectors_rules", "detectors_ml", "risk", "explain"],
      skipped_tools: [],
      execution_timings_ms: { eda: 14.1, features: 9.3, detectors_rules: 12.0, detectors_ml: 19.4, risk: 4.1, explain: 14.2 },
      total_execution_time_ms: 73.1,
      status: "SUCCESS",
      error_message: null,
      created_at: new Date().toISOString(),
    },
    explanations: [
      {
        flag_id: "FLAG-MOCK-ENT-01",
        typology: "Pass-through",
        explanation: "Customer 4521 exhibited high-velocity pass-through conduit activity matching layering typology.",
      },
    ],
    eda_summary: {
      total_transactions: 5,
      total_volume: 55000.0,
      distinct_counterparties: 4,
    },
  },
};

export function getMockResponseForQuery(query: string): QueryResponse {
  const q = query.toLowerCase();
  if (q.includes("4521") || q.includes("customer") || q.includes("single")) {
    return MOCK_DEMO_RESPONSES["scenario_4"];
  }
  if (q.includes("10+") || q.includes("10,000") || q.includes("which customers")) {
    return MOCK_DEMO_RESPONSES["scenario_3"];
  }
  if (q.includes("structuring") || q.includes("30 days") || q.includes("pattern")) {
    return MOCK_DEMO_RESPONSES["scenario_2"];
  }
  return MOCK_DEMO_RESPONSES["scenario_1"];
}
